import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
    title: "BlockHopper",
    description: "Generated by create next app",
};

const space_grotesk = Space_Grotesk({
    subsets: ["latin"],
    variable: "--font-space",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${space_grotesk.variable} font-sans antialiased`}>
                {children}
            </body>
        </html>
    );
}
